image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - muhammad-sammy.csharp
    - editorconfig.editorconfig

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true