name: Continuous Integration
on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'

jobs:
#  Disabled until the editorconfig bug can be fixed
#  Reviewers will have to manually review indenting for now.
#
#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2#
#
#      - name: Lint
#        uses: github/super-linter@v3
#        env:
#          SUPPRESS_POSSUM: true
#          LINTER_RULES_PATH: /
#          VALIDATE_EDITORCONFIG: true
#          EDITORCONFIG_FILE_NAME: .editorconfig
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Test
        run: dotnet test --logger "trx;LogFileName=TestResults-Vignette.Game.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: TestResults-Vignette.Game.Tests
          path: ${{ github.workspace }}/Vignette.Game.Tests/TestResults/TestResults-Vignette.Game.Tests.trx
